language: node_js
node_js:
  - "0.12"
addons:
  firefox: "39.0"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
  # Starting web server.
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  # Install dependencies
  - npm install -g gulp jspm
  - jspm -y install

script: gulp test
